kind: Project
role: standalone
id: tmax-kpiui
catalogId: t-max
name: KPIUI
root: .
defaultBranch: master
parentGroup: t-max
localPathsRef: t-max
sharedContext: t-max-xiaoneng
repositories:
  - id: KPIUI
    name: KPIUI
    localPathKey: KPIUI
    mount: ../../.local/t-max/mounts/repos/KPIUI
    remote: http://10.10.103.4/T-MAX/max-kpi-ui
