kind: Project
id: tmax-dcm
name: dcm
root: .
defaultBranch: master
parentGroup: t-max
sharedContext: t-max-xiaoneng
repositories:
  - id: dcm
    name: dcm
    localPathKey: dcm
    mount: ../../../../.local/t-max/mounts/repos/dcm
    remote: http://10.10.103.4/T-MAX/max-dcm-ui
