kind: Project
id: tmax-dcm
name: dcm
root: .
defaultBranch: master
parentGroup: t-max
knowledgeBindings:
  - knowledgeId: know_tmax_dcm_ima
    source: ima
    locator: tmax-dcm
    scope: tmax-dcm
    revision: pending-live-resolution
    digest: sha256:628e6eae1bc2ea408a1abdf5f5f740dee509ef7bc63e605fab612e63f19eb7aa
    readOnly: true
    trust: external
    requiredCapabilities:
      - read_knowledge
repositories:
  - id: dcm
    name: dcm
    localPathKey: dcm
    mount: ../../../../.local/t-max/mounts/repos/dcm
    remote: http://10.10.103.4/T-MAX/max-dcm-ui
